[2025-01-20 21:00:50,163: INFO: main: Data Ingestion Stage Started >>>>>>>>>>>>>>>>>>>>>]
[2025-01-20 21:00:50,165: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-20 21:00:50,166: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-20 21:00:50,167: INFO: common: created directory at: artifacts]
[2025-01-20 21:00:50,167: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-20 21:00:50,858: INFO: data_ingestion: artifacts/data_ingestion/data.zip downloaded, with the folowing info: 
Connection: close
Content-Length: 7903594
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "dbc016a060da18070593b83afff580c9b300f0b6ea4147a7988433e04df246ca"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: E9CC:1B564D:1EB75C:2286CB:678EFFD0
Accept-Ranges: bytes
Date: Tue, 21 Jan 2025 02:00:49 GMT
Via: 1.1 varnish
X-Served-By: cache-lga21980-LGA
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1737424850.585897,VS0,VE139
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: c8905f9a9458f8cb367a749bce82791d965f0cf1
Expires: Tue, 21 Jan 2025 02:05:49 GMT
Source-Age: 0

]
[2025-01-20 21:00:50,978: INFO: main: Data Ingestion Stage completed >>>>>>>>>>>>>>>>>>>>>]
[2025-01-21 13:14:01,823: INFO: main: Data Ingestion Stage Started >>>>>>>>>>>>>>>>>>>>>]
[2025-01-21 13:14:01,834: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 13:14:01,843: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 13:14:01,844: INFO: common: created directory at: artifacts]
[2025-01-21 13:14:01,844: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-21 13:14:01,845: INFO: data_ingestion: File already exists of size: ~ 7718 KB]
[2025-01-21 13:14:01,952: INFO: main: Data Ingestion Stage completed >>>>>>>>>>>>>>>>>>>>>]
[2025-01-21 13:14:01,952: INFO: main: Data Validation Stage Started >>>>>>>>>>>>>>>>>>>>>]
[2025-01-21 13:14:01,954: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 13:14:01,954: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 13:14:01,955: INFO: common: created directory at: artifacts]
[2025-01-21 13:14:01,955: INFO: common: created directory at: artifacts/data_validation]
[2025-01-21 13:14:01,956: INFO: data_validation: Data validation unsuccessful.]
[2025-01-21 13:14:01,956: INFO: data_validation: Data Validation Succesful.]
[2025-01-21 13:14:01,957: INFO: data_validation: Data Validation Succesful.]
[2025-01-21 13:14:01,957: INFO: data_validation: Data Validation Succesful.]
[2025-01-21 13:14:01,957: INFO: main: Data Validation Stage completed >>>>>>>>>>>>>>>>>>>>>]
[2025-01-21 14:37:46,611: INFO: config: PyTorch version 2.5.1+cu118 available.]
[2025-01-21 14:37:46,612: INFO: config: TensorFlow version 2.18.0 available.]
[2025-01-21 14:37:46,828: INFO: main: Data Ingestion Stage Started >>>>>>>>>>>>>>>>>>>>>]
[2025-01-21 14:37:46,830: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 14:37:46,830: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 14:37:46,831: INFO: common: created directory at: artifacts]
[2025-01-21 14:37:46,831: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-21 14:37:48,370: INFO: data_ingestion: artifacts/data_ingestion/data.zip downloaded, with the folowing info: 
Connection: close
Content-Length: 7903594
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "dbc016a060da18070593b83afff580c9b300f0b6ea4147a7988433e04df246ca"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: A34E:220E00:1DD385:21297F:678FF788
Accept-Ranges: bytes
Date: Tue, 21 Jan 2025 19:37:47 GMT
Via: 1.1 varnish
X-Served-By: cache-nyc-kteb1890022-NYC
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1737488267.898435,VS0,VE155
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 1c90cf92b09ff12c744d799056911868b86772c2
Expires: Tue, 21 Jan 2025 19:42:47 GMT
Source-Age: 0

]
[2025-01-21 14:37:48,480: INFO: main: Data Ingestion Stage completed >>>>>>>>>>>>>>>>>>>>>]
[2025-01-21 14:37:48,480: INFO: main: Data Validation Stage Started >>>>>>>>>>>>>>>>>>>>>]
[2025-01-21 14:37:48,482: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 14:37:48,484: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 14:37:48,484: INFO: common: created directory at: artifacts]
[2025-01-21 14:37:48,485: INFO: common: created directory at: artifacts/data_validation]
[2025-01-21 14:37:48,485: INFO: data_validation: Data validation unsuccessful.]
[2025-01-21 14:37:48,485: INFO: data_validation: Data Validation Succesful.]
[2025-01-21 14:37:48,486: INFO: data_validation: Data Validation Succesful.]
[2025-01-21 14:37:48,486: INFO: data_validation: Data Validation Succesful.]
[2025-01-21 14:37:48,487: INFO: main: Data Validation Stage completed >>>>>>>>>>>>>>>>>>>>>]
[2025-01-21 14:37:48,487: INFO: main: Data Transformation Stage Started >>>>>>>>>>>>>>>>>>>>>]
[2025-01-21 14:37:48,487: ERROR: main: DataTransformationForTraining.main() takes 0 positional arguments but 1 was given]
Traceback (most recent call last):
  File "C:\Projects\python\text-summarizer\main.py", line 34, in <module>
    data_transformation.main()
TypeError: DataTransformationForTraining.main() takes 0 positional arguments but 1 was given
[2025-01-21 14:40:38,896: INFO: config: PyTorch version 2.5.1+cu118 available.]
[2025-01-21 14:40:38,898: INFO: config: TensorFlow version 2.18.0 available.]
[2025-01-21 14:40:39,082: INFO: main: Data Ingestion Stage Started >>>>>>>>>>>>>>>>>>>>>]
[2025-01-21 14:40:39,083: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 14:40:39,084: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 14:40:39,084: INFO: common: created directory at: artifacts]
[2025-01-21 14:40:39,085: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-21 14:40:39,584: INFO: data_ingestion: artifacts/data_ingestion/data.zip downloaded, with the folowing info: 
Connection: close
Content-Length: 7903594
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "dbc016a060da18070593b83afff580c9b300f0b6ea4147a7988433e04df246ca"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: A34E:220E00:1DD385:21297F:678FF788
Accept-Ranges: bytes
Date: Tue, 21 Jan 2025 19:40:39 GMT
Via: 1.1 varnish
X-Served-By: cache-nyc-kteb1890067-NYC
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1737488439.133677,VS0,VE1
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 687d89cd9442afa4bea96e2ac5df933c300e3a77
Expires: Tue, 21 Jan 2025 19:45:39 GMT
Source-Age: 172

]
[2025-01-21 14:40:39,693: INFO: main: Data Ingestion Stage completed >>>>>>>>>>>>>>>>>>>>>]
[2025-01-21 14:40:39,693: INFO: main: Data Validation Stage Started >>>>>>>>>>>>>>>>>>>>>]
[2025-01-21 14:40:39,695: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 14:40:39,696: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 14:40:39,697: INFO: common: created directory at: artifacts]
[2025-01-21 14:40:39,697: INFO: common: created directory at: artifacts/data_validation]
[2025-01-21 14:40:39,698: INFO: data_validation: Data validation unsuccessful.]
[2025-01-21 14:40:39,698: INFO: data_validation: Data Validation Succesful.]
[2025-01-21 14:40:39,699: INFO: data_validation: Data Validation Succesful.]
[2025-01-21 14:40:39,699: INFO: data_validation: Data Validation Succesful.]
[2025-01-21 14:40:39,699: INFO: main: Data Validation Stage completed >>>>>>>>>>>>>>>>>>>>>]
[2025-01-21 14:40:39,701: INFO: main: Data Transformation Stage Started >>>>>>>>>>>>>>>>>>>>>]
[2025-01-21 14:40:39,702: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 14:40:39,703: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 14:40:39,703: INFO: common: created directory at: artifacts]
[2025-01-21 14:40:39,704: INFO: common: created directory at: artifacts/data_transformation]
[2025-01-21 14:40:42,439: INFO: main: Data Transformation Stage completed >>>>>>>>>>>>>>>>>>>>>]
[2025-01-22 09:47:10,093: INFO: config: PyTorch version 2.5.1+cu118 available.]
[2025-01-22 09:47:10,096: INFO: config: TensorFlow version 2.18.0 available.]
[2025-01-23 11:05:47,351: INFO: config: PyTorch version 2.5.1+cu118 available.]
[2025-01-23 11:05:47,354: INFO: config: TensorFlow version 2.18.0 available.]
[2025-01-23 11:05:55,480: WARNING: module_wrapper: From C:\Projects\python\mainenv\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.
]
[2025-01-23 11:05:56,015: INFO: main: Data Ingestion Stage Started >>>>>>>>>>>>>>>>>>>>>]
[2025-01-23 11:05:56,018: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-23 11:05:56,019: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-23 11:05:56,020: INFO: common: created directory at: artifacts]
[2025-01-23 11:05:56,021: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-23 11:05:57,664: INFO: data_ingestion: artifacts/data_ingestion/data.zip downloaded, with the folowing info: 
Connection: close
Content-Length: 7903594
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "dbc016a060da18070593b83afff580c9b300f0b6ea4147a7988433e04df246ca"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 870A:C9F5C:32BE9:385DA:679268E1
Accept-Ranges: bytes
Date: Thu, 23 Jan 2025 16:05:56 GMT
Via: 1.1 varnish
X-Served-By: cache-ewr-kewr1740025-EWR
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1737648356.447092,VS0,VE179
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: b10e95ff2a71a41207cf7f39bdca8fa7d838c1f8
Expires: Thu, 23 Jan 2025 16:10:56 GMT
Source-Age: 0

]
[2025-01-23 11:05:57,847: INFO: main: Data Ingestion Stage completed >>>>>>>>>>>>>>>>>>>>>]
[2025-01-23 11:05:57,847: INFO: main: Data Validation Stage Started >>>>>>>>>>>>>>>>>>>>>]
[2025-01-23 11:05:57,849: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-23 11:05:57,851: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-23 11:05:57,851: INFO: common: created directory at: artifacts]
[2025-01-23 11:05:57,852: INFO: common: created directory at: artifacts/data_validation]
[2025-01-23 11:05:57,853: INFO: data_validation: Data validation unsuccessful.]
[2025-01-23 11:05:57,853: INFO: data_validation: Data Validation Succesful.]
[2025-01-23 11:05:57,854: INFO: data_validation: Data Validation Succesful.]
[2025-01-23 11:05:57,854: INFO: data_validation: Data Validation Succesful.]
[2025-01-23 11:05:57,854: INFO: main: Data Validation Stage completed >>>>>>>>>>>>>>>>>>>>>]
[2025-01-23 11:05:57,854: INFO: main: Data Transformation Stage Started >>>>>>>>>>>>>>>>>>>>>]
[2025-01-23 11:05:57,856: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-23 11:05:57,858: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-23 11:05:57,858: INFO: common: created directory at: artifacts]
[2025-01-23 11:05:57,860: INFO: common: created directory at: artifacts/data_transformation]
[2025-01-23 11:06:00,884: INFO: main: Data Transformation Stage completed >>>>>>>>>>>>>>>>>>>>>]
[2025-01-23 11:06:00,884: INFO: main: Model Training Stage Started >>>>>>>>>>>>>>>>>>>>>]
[2025-01-23 11:06:00,886: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-23 11:06:00,887: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-23 11:06:00,888: INFO: common: created directory at: artifacts]
[2025-01-23 11:06:00,888: INFO: common: created directory at: artifacts/model]
[2025-01-23 11:14:55,185: INFO: main: Model Training Stage completed >>>>>>>>>>>>>>>>>>>>>]
[2025-01-23 15:14:52,230: INFO: config: PyTorch version 2.5.1+cu118 available.]
[2025-01-23 15:14:52,232: INFO: config: TensorFlow version 2.18.0 available.]
[2025-01-23 15:14:57,445: WARNING: module_wrapper: From C:\Projects\python\mainenv\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.
]
[2025-01-23 15:14:57,945: INFO: main: Data Ingestion Stage Started >>>>>>>>>>>>>>>>>>>>>]
[2025-01-23 15:14:57,947: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-23 15:14:57,947: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-23 15:14:57,949: INFO: common: created directory at: artifacts]
[2025-01-23 15:14:57,949: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-23 15:14:58,954: INFO: data_ingestion: artifacts/data_ingestion/data.zip downloaded, with the folowing info: 
Connection: close
Content-Length: 7903594
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "dbc016a060da18070593b83afff580c9b300f0b6ea4147a7988433e04df246ca"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 705E:2E785C:1E4352:216939:6792A342
Accept-Ranges: bytes
Date: Thu, 23 Jan 2025 20:14:58 GMT
Via: 1.1 varnish
X-Served-By: cache-nyc-kteb1890023-NYC
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1737663298.029861,VS0,VE402
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: af7f6602f5b85f82810a5b8168a1d3ed9161e6e5
Expires: Thu, 23 Jan 2025 20:19:58 GMT
Source-Age: 0

]
[2025-01-23 15:14:59,068: INFO: main: Data Ingestion Stage completed >>>>>>>>>>>>>>>>>>>>>]
[2025-01-23 15:14:59,068: INFO: main: Data Validation Stage Started >>>>>>>>>>>>>>>>>>>>>]
[2025-01-23 15:14:59,071: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-23 15:14:59,072: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-23 15:14:59,073: INFO: common: created directory at: artifacts]
[2025-01-23 15:14:59,074: INFO: common: created directory at: artifacts/data_validation]
[2025-01-23 15:14:59,075: INFO: data_validation: Data validation unsuccessful.]
[2025-01-23 15:14:59,075: INFO: data_validation: Data Validation Succesful.]
[2025-01-23 15:14:59,076: INFO: data_validation: Data Validation Succesful.]
[2025-01-23 15:14:59,076: INFO: data_validation: Data Validation Succesful.]
[2025-01-23 15:14:59,077: INFO: main: Data Validation Stage completed >>>>>>>>>>>>>>>>>>>>>]
[2025-01-23 15:14:59,077: INFO: main: Data Transformation Stage Started >>>>>>>>>>>>>>>>>>>>>]
[2025-01-23 15:14:59,080: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-23 15:14:59,080: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-23 15:14:59,082: INFO: common: created directory at: artifacts]
[2025-01-23 15:14:59,082: INFO: common: created directory at: artifacts/data_transformation]
[2025-01-23 15:15:01,934: INFO: main: Data Transformation Stage completed >>>>>>>>>>>>>>>>>>>>>]
[2025-01-23 15:15:01,934: INFO: main: Model Training Stage Started >>>>>>>>>>>>>>>>>>>>>]
[2025-01-23 15:15:01,936: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-23 15:15:01,938: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-23 15:15:01,938: INFO: common: created directory at: artifacts]
[2025-01-23 15:15:01,938: INFO: common: created directory at: artifacts/model]
[2025-01-23 15:23:42,980: INFO: main: Model Training Stage completed >>>>>>>>>>>>>>>>>>>>>]
[2025-01-23 15:23:42,987: INFO: main: Model Evaluation Stage Started >>>>>>>>>>>>>>>>>>>>>]
[2025-01-23 15:23:43,005: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-23 15:23:43,012: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-23 15:23:43,013: INFO: common: created directory at: artifacts]
[2025-01-23 15:23:43,014: INFO: common: created directory at: artifacts/model_evaluation]
[2025-01-23 15:28:17,146: INFO: rouge_scorer: Using default tokenizer.]
[2025-01-23 15:28:17,311: INFO: main: Model Evaluation Stage completed >>>>>>>>>>>>>>>>>>>>>]
[2025-01-23 22:55:28,355: INFO: server: Started server process [4092]]
[2025-01-23 22:55:28,357: INFO: on: Waiting for application startup.]
[2025-01-23 22:55:28,357: INFO: on: Application startup complete.]
[2025-01-23 22:55:28,358: INFO: server: Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)]
[2025-01-23 22:56:56,813: ERROR: h11_impl: Exception in ASGI application
]
Traceback (most recent call last):
  File "C:\Projects\python\mainenv\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\python\mainenv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\python\mainenv\Lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Projects\python\mainenv\Lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Projects\python\mainenv\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Projects\python\mainenv\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Projects\python\mainenv\Lib\site-packages\starlette\exceptions.py", line 93, in __call__
    raise exc
  File "C:\Projects\python\mainenv\Lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "C:\Projects\python\mainenv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Projects\python\mainenv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Projects\python\mainenv\Lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "C:\Projects\python\mainenv\Lib\site-packages\starlette\routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "C:\Projects\python\mainenv\Lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\python\mainenv\Lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\python\mainenv\Lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\python\text-summarizer\app.py", line 42, in predict_route
    raise e
  File "C:\Projects\python\text-summarizer\app.py", line 38, in predict_route
    obj = PredictionPipeline()
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\python\text-summarizer\src\textSummarizer\pipeline\prediction.py", line 7, in __init__
    self.config = ConfigurationManager.get_model_evaluation_config()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ConfigurationManager.get_model_evaluation_config() missing 1 required positional argument: 'self'
[2025-01-23 22:58:17,134: INFO: server: Shutting down]
[2025-01-23 22:58:17,242: INFO: on: Waiting for application shutdown.]
[2025-01-23 22:58:17,243: INFO: on: Application shutdown complete.]
[2025-01-23 22:58:17,243: INFO: server: Finished server process [4092]]
[2025-01-23 22:58:33,426: INFO: server: Started server process [27816]]
[2025-01-23 22:58:33,427: INFO: on: Waiting for application startup.]
[2025-01-23 22:58:33,428: INFO: on: Application startup complete.]
[2025-01-23 22:58:33,428: INFO: server: Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)]
[2025-01-23 22:58:59,215: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-23 22:58:59,217: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-23 22:58:59,218: INFO: common: created directory at: artifacts]
[2025-01-23 22:58:59,218: INFO: common: created directory at: artifacts/model_evaluation]
[2025-01-23 22:59:03,947: WARNING: module_wrapper: From C:\Projects\python\mainenv\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.
]
[2025-01-23 23:00:27,867: INFO: server: Shutting down]
[2025-01-23 23:00:27,975: INFO: on: Waiting for application shutdown.]
[2025-01-23 23:00:27,976: INFO: on: Application shutdown complete.]
[2025-01-23 23:00:27,977: INFO: server: Finished server process [27816]]
[2025-01-23 23:25:29,138: INFO: server: Started server process [18132]]
[2025-01-23 23:25:29,139: INFO: on: Waiting for application startup.]
[2025-01-23 23:25:29,140: INFO: on: Application startup complete.]
[2025-01-23 23:25:29,140: INFO: server: Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)]
[2025-01-23 23:26:20,647: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-23 23:26:20,662: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-23 23:26:20,663: INFO: common: created directory at: artifacts]
[2025-01-23 23:26:20,664: INFO: common: created directory at: artifacts/model_evaluation]
[2025-01-23 23:26:25,828: WARNING: module_wrapper: From C:\Projects\python\mainenv\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.
]
[2025-01-23 23:29:21,621: INFO: server: Shutting down]
[2025-01-23 23:29:21,737: INFO: on: Waiting for application shutdown.]
[2025-01-23 23:29:21,738: INFO: on: Application shutdown complete.]
[2025-01-23 23:29:21,738: INFO: server: Finished server process [18132]]
[2025-01-25 17:35:02,315: INFO: config: PyTorch version 2.5.1+cu118 available.]
[2025-01-25 17:35:02,317: INFO: config: TensorFlow version 2.18.0 available.]
[2025-01-25 17:35:08,626: WARNING: module_wrapper: From C:\Projects\python\mainenv\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.
]
[2025-01-25 17:35:09,232: INFO: main: Data Ingestion Stage Started >>>>>>>>>>>>>>>>>>>>>]
[2025-01-25 17:35:09,242: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-25 17:35:09,243: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-25 17:35:09,244: INFO: common: created directory at: artifacts]
[2025-01-25 17:35:09,244: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-25 17:35:22,003: INFO: data_ingestion: artifacts/data_ingestion/data.zip downloaded, with the folowing info: 
X-GUploader-UploadID: AFIdbgRn4BrcKk0WRZxnLZ1fIUsh5v9uIn_n0HfQdWT0PZLze-wnsSwIKJdQhnq3AjxgxuCu
Content-Type: application/octet-stream
Content-Security-Policy: sandbox
Content-Security-Policy: default-src 'none'
Content-Security-Policy: frame-ancestors 'none'
X-Content-Security-Policy: sandbox
Cross-Origin-Opener-Policy: same-origin
Cross-Origin-Embedder-Policy: require-corp
Cross-Origin-Resource-Policy: same-site
X-Content-Type-Options: nosniff
Content-Disposition: attachment; filename="data.zip"
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: false
Access-Control-Allow-Headers: Accept, Accept-Language, Authorization, Cache-Control, Content-Disposition, Content-Encoding, Content-Language, Content-Length, Content-MD5, Content-Range, Content-Type, Date, developer-token, financial-institution-id, X-Goog-Sn-Metadata, X-Goog-Sn-PatientId, GData-Version, google-cloud-resource-prefix, linked-customer-id, login-customer-id, x-goog-request-params, Host, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Origin, OriginToken, Pragma, Range, request-id, Slug, Transfer-Encoding, hotrod-board-name, hotrod-chrome-cpu-model, hotrod-chrome-processors, Want-Digest, X-Ad-Manager-Impersonation, x-chrome-connected, X-ClientDetails, X-Client-Pctx, X-Client-Version, x-debug-settings-metadata, X-Firebase-Locale, X-Goog-Firebase-Installations-Auth, X-Firebase-Client, X-Firebase-Client-Log-Type, X-Firebase-GMPID, X-Firebase-Auth-Token, X-Firebase-AppCheck, X-Firebase-Token, X-Goog-Drive-Client-Version, X-Goog-Drive-Resource-Keys, X-GData-Client, X-GData-Key, X-GoogApps-Allowed-Domains, X-Goog-AdX-Buyer-Impersonation, X-Goog-Api-Client, X-Goog-Visibilities, X-Goog-AuthUser, X-Google-EOM, x-goog-ext-124712974-jspb, x-goog-ext-467253834-jspb, x-goog-ext-353267353-bin, x-goog-ext-353267353-jspb, x-goog-ext-251363160-jspb, x-goog-ext-259736195-jspb, x-goog-ext-477772811-jspb, x-goog-ext-359275022-bin, x-goog-ext-328800237-jspb, x-goog-ext-202735639-bin, x-goog-ext-223435598-bin, X-Goog-PageId, X-Goog-Encode-Response-If-Executable, X-Goog-Correlation-Id, X-Goog-Request-Info, X-Goog-Request-Reason, X-Goog-Request-Time, X-Goog-Experiments, x-goog-iam-authority-selector, x-goog-iam-authorization-token, X-Goog-Spatula, X-Goog-Travel-Bgr, X-Goog-Travel-Settings, X-Goog-Upload-Command, X-Goog-Upload-Content-Disposition, X-Goog-Upload-Content-Length, X-Goog-Upload-Content-Type, X-Goog-Upload-File-Name, X-Goog-Upload-Header-Content-Encoding, X-Goog-Upload-Header-Content-Length, X-Goog-Upload-Header-Content-Type, X-Goog-Upload-Header-Transfer-Encoding, X-Goog-Upload-Offset, X-Goog-Upload-Protocol, x-goog-user-project, X-Goog-Visitor-Id, X-Goog-FieldMask, X-Google-Project-Override, x-goog-maps-api-salt, x-goog-maps-api-signature, x-goog-maps-client-id, X-Goog-Api-Key, x-goog-spanner-database-role, X-HTTP-Method-Override, X-JavaScript-User-Agent, X-Pan-Versionid, X-Proxied-User-IP, X-Origin, X-Referer, X-Requested-With, X-Stadia-Client-Context, X-Upload-Content-Length, X-Upload-Content-Type, X-Use-Alt-Service, X-Use-HTTP-Status-Code-Override, X-Ios-Bundle-Identifier, X-Places-Ios-Sdk, X-Android-Package, X-Android-Cert, X-Places-Android-Sdk, X-Goog-Maps-Ios-Uuid, X-Goog-Maps-Android-Uuid, X-Ariane-Xsrf-Token, X-YouTube-Bootstrap-Logged-In, X-YouTube-VVT, X-YouTube-Page-CL, X-YouTube-Page-Timestamp, X-Compass-Routing-Destination, x-framework-xsrf-token, X-Goog-Meeting-ABR, X-Goog-Meeting-Botguardid, X-Goog-Meeting-Bot-Info, X-Goog-Meeting-ClientInfo, X-Goog-Meeting-ClientVersion, X-Goog-Meeting-Debugid, X-Goog-Meeting-Identifier, X-Goog-Meeting-Interop-Cohorts, X-Goog-Meeting-Interop-Type, X-Goog-Meeting-OidcIdToken, X-Goog-Meeting-RtcClient, X-Goog-Meeting-StartSource, X-Goog-Meeting-Token, X-Goog-Meeting-Viewer-Token, X-Client-Data, x-sdm-id-token, X-Sfdc-Authorization, MIME-Version, Content-Transfer-Encoding, X-Earth-Engine-App-ID-Token, X-Earth-Engine-Computation-Profile, X-Earth-Engine-Computation-Profiling, X-Play-Console-Experiments-Override, X-Play-Console-Session-Id, x-alkali-account-key, x-alkali-application-key, x-alkali-auth-apps-namespace, x-alkali-auth-entities-namespace, x-alkali-auth-entity, x-alkali-client-locale, EES-S7E-MODE, cast-device-capabilities, X-Server-Timeout, x-foyer-client-environment, x-goog-greenenergyuserappservice-metadata, x-goog-sherlog-context, X-Server-Token, x-rfui-request-context, x-goog-nest-jwt, X-Cloud-Trace-Context, traceparent, x-goog-chat-space-id, x-goog-pan-request-context, X-AppInt-Credentials
Access-Control-Allow-Methods: GET,HEAD,OPTIONS
Accept-Ranges: bytes
Content-Length: 11692487
Last-Modified: Sat, 25 Jan 2025 20:07:37 GMT
Date: Sat, 25 Jan 2025 22:35:20 GMT
Expires: Sat, 25 Jan 2025 22:35:20 GMT
Cache-Control: private, max-age=0
X-Goog-Hash: crc32c=MVGb6w==
Server: UploadServer
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Connection: close

]
[2025-01-25 17:35:22,135: INFO: main: Data Ingestion Stage completed >>>>>>>>>>>>>>>>>>>>>]
[2025-01-25 17:35:22,135: INFO: main: Data Validation Stage Started >>>>>>>>>>>>>>>>>>>>>]
[2025-01-25 17:35:22,138: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-25 17:35:22,140: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-25 17:35:22,140: INFO: common: created directory at: artifacts]
[2025-01-25 17:35:22,141: INFO: common: created directory at: artifacts/data_validation]
[2025-01-25 17:35:22,141: INFO: data_validation: Data validation unsuccessful.]
[2025-01-25 17:35:22,142: INFO: data_validation: Data Validation Succesful.]
[2025-01-25 17:35:22,143: INFO: data_validation: Data Validation Succesful.]
[2025-01-25 17:35:22,143: INFO: data_validation: Data Validation Succesful.]
[2025-01-25 17:35:22,143: INFO: main: Data Validation Stage completed >>>>>>>>>>>>>>>>>>>>>]
[2025-01-25 17:35:22,144: INFO: main: Data Transformation Stage Started >>>>>>>>>>>>>>>>>>>>>]
[2025-01-25 17:35:22,145: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-25 17:35:22,147: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-25 17:35:22,148: INFO: common: created directory at: artifacts]
[2025-01-25 17:35:22,148: INFO: common: created directory at: artifacts/data_transformation]
[2025-01-25 17:35:22,858: INFO: main: Data Transformation Stage completed >>>>>>>>>>>>>>>>>>>>>]
[2025-01-25 17:35:22,858: INFO: main: Model Training Stage Started >>>>>>>>>>>>>>>>>>>>>]
[2025-01-25 17:35:22,860: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-25 17:35:22,862: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-25 17:35:22,862: INFO: common: created directory at: artifacts]
[2025-01-25 17:35:22,863: INFO: common: created directory at: artifacts/model]
[2025-01-25 17:35:24,590: ERROR: main: 'train']
Traceback (most recent call last):
  File "C:\Projects\python\text-summarizer\main.py", line 47, in <module>
    model_training.main()
  File "C:\Projects\python\text-summarizer\src\textSummarizer\pipeline\stage_04_model_trainer.py", line 13, in main
    model_trainer_config.train()
  File "c:\projects\python\text-summarizer\src\textSummarizer\components\model_trainer.py", line 46, in train
    train_dataset=dataset_samsum_pt['train'],
                  ~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Projects\python\mainenv\Lib\site-packages\datasets\dataset_dict.py", line 72, in __getitem__
    return super().__getitem__(k)
           ^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'train'
